### ISSUE TITLE
`request` module is deprecated

### ISSUE THREAD

**Issue by imgx64** [loopbackio/strong-soap#262]
# Description/Steps to reproduce

The [`request`](https://www.npmjs.com/package/request) module README says:

> # Deprecated!
> 
> As of Feb 11th 2020, request is fully deprecated. No new changes are expected to land. In fact, none have landed for some time.
> 
> For more information about why request is deprecated and possible alternatives refer to
> [this issue](https://github.com/request/request/issues/3142).

# Link to reproduction sandbox
```
$ npm install strong-soap
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142 
```

# Expected result
`request` should be replaced with a different http client library.

**Comment by dhmlau** [comment]
We switched to use `axios` in some of the modules in `loopback-next`.  @raymondfeng, do you think it would be a good choice for this module too? Thanks.
