### ISSUE TITLE
Query regarding restricting XSD files referenced in WSDL

### ISSUE THREAD

**Issue by Dsiddhesh** [loopbackio/strong-soap#297]
# Description

Hi All, We need to parse a Oracle EBS WSDL to get Customer information. We tried SOAP model utility to form a model using desired operation from WSDL successfully but we see that WSDL processing takes lot of time in createClient call itself. 
We added log inside wsdl.js [open ](https://github.com/strongloop/strong-soap/blob/master/src/parser/wsdl.js#L440) method and see that all XSD's are getting processed. There are many  XSD's in WSDL and are referenced using http. 
We wanted to know if there is any way where in we can include only required XSD's or do away with processing of unwanted  XSD's.

**Comment by raymondfeng** [comment]
1. You can probably use WSDL_CACHE as a workaround. See https://github.com/strongloop/strong-soap/blob/master/src/parser/wsdl.js#L39. A pre-populated can be passed in via `options`.

**Comment by Dsiddhesh** [comment]
@raymondfeng I tried approach of using WSDL_CACHE . I see that first request to soap.createClient takes lot of time but subsequent requests take very less time as I understand that WSDL is cached. But our requirement is to call soap.createClient method only once. Is there any way to restrict processing of wsdl during first call to soap.createClient ?

**Comment by raymondfeng** [comment]
@Dsiddhesh We use WSDL_CACHE for XSDs too. See https://github.com/strongloop/strong-soap/blob/1a3bf3001202efc82c8c20ba4baba522d99881c8/src/parser/wsdl.js#L189. If you populate `options.WSDL_CACHE` upfront with the calculated includePath as the key, the corresponding xsd should be loaded from cache.

**Comment by Dsiddhesh** [comment]
@raymondfeng  Thanks for clarification. I dint get more details in documentation about options.WSDL_CACHE. Have below queries
1) What is the duration of caching ? few days, hour ? can this be changed ? 
2) Any memory related restrictions that we should take care ?

**Comment by raymondfeng** [comment]
The cache is for the wsdl/xsd only by urls during WSDL parsing. It is held as a property of the `WSDL` instance (https://github.com/strongloop/strong-soap/blob/master/src/parser/wsdl.js#L39). The WSDL instance should be subject to GC after parsing.
