### ISSUE TITLE
Update `xml-crypto` dependency to `^2.0.0` in version 1.22.1 and publish new `1.X.X` version as PATCH or MINOR

### ISSUE THREAD

**Issue by marcosins** [loopbackio/strong-soap#300]
# Description
**Feature request:** I would like you to consider updating `xml-crypto` to version `^2.0.0` in `strong-soap@1.22.1` and up.

`xml-crypto@2.0.0` solves an [Improper Key Verification vulnerability](https://www.npmjs.com/advisories/1583) by disabling by default support for the HMAC-SHA1 'signing' algorithm, as described in [their release page](https://github.com/yaronn/xml-crypto/releases/tag/v2.0.0).

For tag `1.22.1` the only instance were `strong-soap` uses `xml-crypto` is here in `WSSecurityCert.js`:
https://github.com/strongloop/strong-soap/blob/bda154bd9610d9cdfaf0f4c800b11d19bbb5d500/src/security/WSSecurityCert.js#L9

# Expected result

Either `strong-soap@1.22.2` or `strong-soap-@1.23.0` is published with `xml-crypto@2.0.0` as dependency.

# Additional information
- linux x64 12.20.0

**Comment by dhmlau** [comment]
@marcosins, would you like to submit a PR? Thanks.

**Comment by marcosins** [comment]
Hi @dhmlau, I published #302. Let me know if anything else needs to be done in order to comply with your contributing guidelines.

**Comment by marcosins** [comment]
I'm submitting again my changes in #305 with more clean commits
