### ISSUE TITLE
Peer Dependencies clarification

### ISSUE THREAD

**Issue by sumitkhetrapal** [loopbackio/strong-soap#350]
Current node module hierarchy is :
`Strong-soap`  pulls -> `httpntlm-maa` which internally consumes `request` and `node-fetch` as peer deps

As a consumer of package, do we ensure that peerDeps are satisfied or you are expecting it to be managed by the consumer of `strong-soap` itself?

Ref: https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by achrinza** [comment]
`httpntlm-maa` will import either `request` or `node-fetch` depending on which are available in the `node_modules` tree. This peer dependency is already satisfied by `strong-soap`'s `request` dependency:

https://github.com/loopbackio/strong-soap/blob/c3a9ebd45c3c0962821629aadeb32c7789b461be/package.json#L17

Hence, consumers of `strong-soap` do not need to ensure that that deep peer dependency is satisfied.

**Comment by sumitkhetrapal** [comment]
In that case, if request is available in node module tree, node-fetch will be skipped. Similarly, if node-fetch is available, request will be skipped.

We should make sure that both the peerDeps are satisfied else the consumer need to handle it explicitly.
Let me know if it is feasible to include both the module under dependencies or not?

**Comment by achrinza** [comment]
> We should make sure that both the peerDeps are satisfied else the consumer need to handle it explicitly.

No explicit handling by the consumer is necessary; Since `request` is already installed by `strong-soap`, `httpntlm-maa` will pick that up without additional configuration.

Adding `node-fetch` would be adding a package that would never be used as it's either `request` or `node-fetch`, not both simultaneously.
