### ISSUE TITLE
Date format Problem in Soap-Client , automatic Z added in Date Formate

### ISSUE THREAD

**Issue by hrushikesh-udchalo** [loopbackio/strong-soap#354]
what i have send 
`
const request = {
...,
TravelDate: new Date('2022-02-08'),
...
}
`
last request xml= >
`<TravelDate>2022-02-08Z</TravelDate>`

**Comment by achrinza** [comment]
I have re-opened https://github.com/loopbackio/strong-soap/issues/289 and will continue tracking the issue there.

**Comment by achrinza** [comment]
Duplicate of #289
