### ISSUE TITLE
Remove deprecated package "request".

### ISSUE THREAD

**Issue by balraju9860** [loopbackio/strong-soap#645]
There is a security vulnerability for a request module which is deprecated.
https://www.npmjs.com/package/request.  This is been used here https://github.com/loopbackio/strong-soap/blob/master/package.json#L14. Can you please remove this package.

**Comment by achrinza** [comment]
Thanks for opening an issue. There's already an existing issue regarding replacing the `request` package: https://github.com/loopbackio/strong-soap/issues/535.

To aid in discussion, we'll consolidate to that issue.

**Comment by achrinza** [comment]
duplicate of https://github.com/loopbackio/strong-soap/issues/535
