### ISSUE TITLE
Move from httpntlm-maa to httpntlm

### ISSUE THREAD

**Issue by jynolen** [loopbackio/strong-soap#693]
# Description

Deps lib  httpntlm-maa is not upgrade anymore and got some issues with crypto.
Following piece of code produce error and made ntlm impossible.
```
function encrypt(buf) {
    var key = insertZerosEvery7Bits(buf);
    var des = crypto.createCipheriv('DES-ECB', key, '');
    return des.update('KGS!@#$%'); // page 57 in [MS-NLMP]);
  }
```

`Error: error:0308010C:digital envelope routines::unsupported`

A drop replace of  httpntlm-maa with  httpntlm does not need any changes rather than import and make ntlm auth passed with success.

**Comment by toddtarsi** [comment]
@jynolen - This is done and can be closed!
