### ISSUE TITLE
Node 22 

### ISSUE THREAD

**Issue by fabiancook** [loopbackio/strong-soap#900]
[Node 22 is now LTS.](https://github.com/nodejs/release#release-schedule)

This package does not allow node version 22 

https://github.com/loopbackio/strong-soap/blob/815a8a4b4e5c1f986c64f94d282bffc866262400/package.json#L6

Is there any changes that need to be made to the module other than the engines field?

**Comment by achrinza** [comment]
Closed by: https://github.com/loopbackio/strong-soap/pull/901
